---
title: "ICCAT Assessments"
author: "Conner Smith"
date: "6/16/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(here)
library(tidyverse)

load(here("data", "DBdata[asmt][v4.495].RData"))
```


## ALBANATL (no update, jsut pulling catch)

```{r setup, include=FALSE}
# RAM datasets to use
ram_datasets <- c('timeseries_values_views', 'stock', 'area', 'bioparams', 'timeseries_assessments_views',
                  'bioparams_values_views', 'assessor', 'management', 'assessment')
# Remove all unneccessary RAM data
rm(list = c(ls()[!(ls() %in% ram_datasets)]))

# Extract main RAM timeseries, with BdivBmsypref and UdivUmsypref
albanatl.ram.ts <- timeseries_values_views %>%
  tbl_df() %>%
  select(stockid, stocklong, year, UdivUmsypref, TBbest, TBdivTBmsy, BdivBmsypref, TAC, TCbest, ERbest, SSB, F, FdivFmsy, ) %>% #These are some of the metrics of interest, but this can be changed to select more if needed.
  left_join(tbl_df(stock),by = c("stockid", "stocklong")) %>%
  left_join(tbl_df(area), by = "areaid") %>%
  select(-inmyersdb, -myersstockid, -alternateareaname) %>% 
  filter(stockid == 'ALBANATL') %>% #We are only interested in "country == multinational", so removing the two countries that have pelagic stock assessments that are not multinational.
  select(stockid, year, TCbest)
   #Not one of the RFMOs we're interested in, so removing it.

albanatl.ram.dbase <- albanatl.ram.ts 

write_csv(albanatl.ram.dbase, "/Users/conne/Documents/Fisheries/fish_stuff/data/tuna/albanatl_catch.csv")
```


## ATBTUNAEATL (no update, just pulling catch)

```{r setup, include=FALSE}
# Extract main RAM timeseries, with BdivBmsypref and UdivUmsypref
atbtunaeatl.ram.ts <- timeseries_values_views %>%
  tbl_df() %>%
  select(stockid, stocklong, year, UdivUmsypref, TBbest, TBdivTBmsy, BdivBmsypref, TAC, TCbest, ERbest, SSB, F, FdivFmsy, ) %>% #These are some of the metrics of interest, but this can be changed to select more if needed.
  left_join(tbl_df(stock),by = c("stockid", "stocklong")) %>%
  left_join(tbl_df(area), by = "areaid") %>%
  select(-inmyersdb, -myersstockid, -alternateareaname) %>% 
  filter(stockid == 'ATBTUNAEATL') %>% #We are only interested in "country == multinational", so removing the two countries that have pelagic stock assessments that are not multinational.
  select(stockid, year, TCbest)
   #Not one of the RFMOs we're interested in, so removing it.

atbtunaeatl.ram.dbase <- atbtunaeatl.ram.ts 

write_csv(atbtunaeatl.ram.dbase, "/Users/conne/Documents/Fisheries/fish_stuff/data/tuna/atbtunaeatl_catch.csv")
```

## ALBASATL (no update, just pulling catch)

```{r setup, include=FALSE}
# Extract main RAM timeseries, with BdivBmsypref and UdivUmsypref
albasatl.ram.ts <- timeseries_values_views %>%
  tbl_df() %>%
  select(stockid, stocklong, year, UdivUmsypref, TBbest, TBdivTBmsy, BdivBmsypref, TAC, TCbest, ERbest, SSB, F, FdivFmsy, ) %>% #These are some of the metrics of interest, but this can be changed to select more if needed.
  left_join(tbl_df(stock),by = c("stockid", "stocklong")) %>%
  left_join(tbl_df(area), by = "areaid") %>%
  select(-inmyersdb, -myersstockid, -alternateareaname) %>% 
  filter(stockid == 'ALBASATL') %>% #We are only interested in "country == multinational", so removing the two countries that have pelagic stock assessments that are not multinational.
  select(stockid, year, TCbest)
   #Not one of the RFMOs we're interested in, so removing it.

albasatl.ram.dbase <- albasatl.ram.ts 

write_csv(albasatl.ram.dbase, "/Users/conne/Documents/Fisheries/fish_stuff/data/tuna/albasatl_catch.csv")
```

## BIGEYEATL (no update, just pulling catch)
```{r setup, include=FALSE}
# Extract main RAM timeseries, with BdivBmsypref and UdivUmsypref
bigeyeatl.ram.ts <- timeseries_values_views %>%
  tbl_df() %>%
  select(stockid, stocklong, year, UdivUmsypref, TBbest, TBdivTBmsy, BdivBmsypref, TAC, TCbest, ERbest, SSB, F, FdivFmsy, ) %>% #These are some of the metrics of interest, but this can be changed to select more if needed.
  left_join(tbl_df(stock),by = c("stockid", "stocklong")) %>%
  left_join(tbl_df(area), by = "areaid") %>%
  select(-inmyersdb, -myersstockid, -alternateareaname) %>% 
  filter(stockid == 'BIGEYEATL') %>% #We are only interested in "country == multinational", so removing the two countries that have pelagic stock assessments that are not multinational.
  select(stockid, year, TCbest)
   #Not one of the RFMOs we're interested in, so removing it.

bigeyeatl.ram.dbase <- bigeyeatl.ram.ts 

write_csv(bigeyeatl.ram.dbase, "/Users/conne/Documents/Fisheries/fish_stuff/data/tuna/bigeyeatl_catch.csv")
```

## SKJCWATL (ENDS IN 2013)

```{r}
# Extract main RAM timeseries, with BdivBmsypref and UdivUmsypref
skjwatl.ram.ts <- timeseries_values_views %>%
  tbl_df() %>%
  select(stockid, stocklong, year, UdivUmsypref, TBbest, TBdivTBmsy, BdivBmsypref, TAC, TCbest, ERbest, SSB, F, FdivFmsy, ) %>% #These are some of the metrics of interest, but this can be changed to select more if needed.
  left_join(tbl_df(stock),by = c("stockid", "stocklong")) %>%
  left_join(tbl_df(area), by = "areaid") %>%
  select(-inmyersdb, -myersstockid, -alternateareaname) %>% 
  filter(stockid == 'SKJWATL') %>% #We are only interested in "country == multinational", so removing the two countries that have pelagic stock assessments that are not multinational.
  select(stockid, year, TCbest)
   #Not one of the RFMOs we're interested in, so removing it.

skjwatl.ram.dbase <- skjwatl.ram.ts 

write_csv(skjwatl.ram.dbase, "/Users/conne/Documents/Fisheries/fish_stuff/data/tuna/skjwatl_catch.csv")
```

## YFINATL (Ends in 2016)

```{r}
# Extract main RAM timeseries, with BdivBmsypref and UdivUmsypref
yfinatl.ram.ts <- timeseries_values_views %>%
  tbl_df() %>%
  select(stockid, stocklong, year, UdivUmsypref, TBbest, TBdivTBmsy, BdivBmsypref, TAC, TCbest, ERbest, SSB, F, FdivFmsy, ) %>% #These are some of the metrics of interest, but this can be changed to select more if needed.
  left_join(tbl_df(stock),by = c("stockid", "stocklong")) %>%
  left_join(tbl_df(area), by = "areaid") %>%
  select(-inmyersdb, -myersstockid, -alternateareaname) %>% 
  filter(stockid == 'YFINATL') %>% #We are only interested in "country == multinational", so removing the two countries that have pelagic stock assessments that are not multinational.
  select(stockid, year, TCbest)
   #Not one of the RFMOs we're interested in, so removing it.

yfinatl.ram.dbase <- yfinatl.ram.ts 

write_csv(yfinatl.ram.dbase, "/Users/conne/Documents/Fisheries/fish_stuff/data/tuna/yfinatl_catch.csv")
```

## BMARLINATL (no update)

```{r}
# Extract main RAM timeseries, with BdivBmsypref and UdivUmsypref
bmarlinatl.ram.ts <- timeseries_values_views %>%
  tbl_df() %>%
  select(stockid, stocklong, year, UdivUmsypref, TBbest, TBdivTBmsy, BdivBmsypref, TAC, TCbest, ERbest, SSB, F, FdivFmsy, ) %>% #These are some of the metrics of interest, but this can be changed to select more if needed.
  left_join(tbl_df(stock),by = c("stockid", "stocklong")) %>%
  left_join(tbl_df(area), by = "areaid") %>%
  select(-inmyersdb, -myersstockid, -alternateareaname) %>% 
  filter(stockid == 'BMARLINATL') %>% #We are only interested in "country == multinational", so removing the two countries that have pelagic stock assessments that are not multinational.
  select(stockid, year, TCbest)
   #Not one of the RFMOs we're interested in, so removing it.

bmarlinatl.ram.dbase <- bmarlinatl.ram.ts 

write_csv(bmarlinatl.ram.dbase, "/Users/conne/Documents/Fisheries/fish_stuff/data/billfish/bmarlinatl_catch.csv")
```


## SAILEATL (no update)

```{r}
# Extract main RAM timeseries, with BdivBmsypref and UdivUmsypref
saileatl.ram.ts <- timeseries_values_views %>%
  tbl_df() %>%
  select(stockid, stocklong, year, UdivUmsypref, TBbest, TBdivTBmsy, BdivBmsypref, TAC, TCbest, ERbest, SSB, F, FdivFmsy, ) %>% #These are some of the metrics of interest, but this can be changed to select more if needed.
  left_join(tbl_df(stock),by = c("stockid", "stocklong")) %>%
  left_join(tbl_df(area), by = "areaid") %>%
  select(-inmyersdb, -myersstockid, -alternateareaname) %>% 
  filter(stockid == 'SAILEATL') %>% #We are only interested in "country == multinational", so removing the two countries that have pelagic stock assessments that are not multinational.
  select(stockid, year, TCbest)
   #Not one of the RFMOs we're interested in, so removing it.

saileatl.ram.dbase <- saileatl.ram.ts 

write_csv(saileatl.ram.dbase, "/Users/conne/Documents/Fisheries/fish_stuff/data/billfish/saileatl_catch.csv")

# Note: only through 2010, updating with more recent numbers and resaving file

```


## SAILWATL (no update)

```{r}
# Extract main RAM timeseries, with BdivBmsypref and UdivUmsypref
sailwatl.ram.ts <- timeseries_values_views %>%
  tbl_df() %>%
  select(stockid, stocklong, year, UdivUmsypref, TBbest, TBdivTBmsy, BdivBmsypref, TAC, TCbest, ERbest, SSB, F, FdivFmsy, ) %>% #These are some of the metrics of interest, but this can be changed to select more if needed.
  left_join(tbl_df(stock),by = c("stockid", "stocklong")) %>%
  left_join(tbl_df(area), by = "areaid") %>%
  select(-inmyersdb, -myersstockid, -alternateareaname) %>% 
  filter(stockid == 'SAILWATL') %>% #We are only interested in "country == multinational", so removing the two countries that have pelagic stock assessments that are not multinational.
  select(stockid, year, TCbest)
   #Not one of the RFMOs we're interested in, so removing it.

sailwatl.ram.dbase <- sailwatl.ram.ts 

write_csv(sailwatl.ram.dbase, "/Users/conne/Documents/Fisheries/fish_stuff/data/billfish/sailwatl_catch.csv")

# Note: only through 2011, updating with more recent numbers and re-saving file

```

## SWORDMED (no update)

```{r}
# Extract main RAM timeseries, with BdivBmsypref and UdivUmsypref
swordmed.ram.ts <- timeseries_values_views %>%
  tbl_df() %>%
  select(stockid, stocklong, year, UdivUmsypref, TBbest, TBdivTBmsy, BdivBmsypref, TAC, TCbest, ERbest, SSB, F, FdivFmsy, ) %>% #These are some of the metrics of interest, but this can be changed to select more if needed.
  left_join(tbl_df(stock),by = c("stockid", "stocklong")) %>%
  left_join(tbl_df(area), by = "areaid") %>%
  select(-inmyersdb, -myersstockid, -alternateareaname) %>% 
  filter(stockid == 'SWORDMED') %>% #We are only interested in "country == multinational", so removing the two countries that have pelagic stock assessments that are not multinational.
  select(stockid, year, TCbest)
   #Not one of the RFMOs we're interested in, so removing it.

swordmed.ram.dbase <- swordmed.ram.ts 

write_csv(swordmed.ram.dbase, "/Users/conne/Documents/Fisheries/fish_stuff/data/billfish/swordmed_catch.csv")

# Note: only through 2009, updating with more recent numbers and re-saving file

```

## SWORDNATL (no update)

```{r}
# Extract main RAM timeseries, with BdivBmsypref and UdivUmsypref
swordnatl.ram.ts <- timeseries_values_views %>%
  tbl_df() %>%
  select(stockid, stocklong, year, UdivUmsypref, TBbest, TBdivTBmsy, BdivBmsypref, TAC, TCbest, ERbest, SSB, F, FdivFmsy, ) %>% #These are some of the metrics of interest, but this can be changed to select more if needed.
  left_join(tbl_df(stock),by = c("stockid", "stocklong")) %>%
  left_join(tbl_df(area), by = "areaid") %>%
  select(-inmyersdb, -myersstockid, -alternateareaname) %>% 
  filter(stockid == 'SWORDNATL') %>% #We are only interested in "country == multinational", so removing the two countries that have pelagic stock assessments that are not multinational.
  select(stockid, year, TCbest)
   #Not one of the RFMOs we're interested in, so removing it.

swordnatl.ram.dbase <- swordnatl.ram.ts 

write_csv(swordnatl.ram.dbase, "/Users/conne/Documents/Fisheries/fish_stuff/data/billfish/swordnatl_catch.csv")

# Note: only through 2013, updating with more recent numbers and re-saving file

```

## SWORDSATL (no update)

```{r}
# Extract main RAM timeseries, with BdivBmsypref and UdivUmsypref
swordsatl.ram.ts <- timeseries_values_views %>%
  tbl_df() %>%
  select(stockid, stocklong, year, UdivUmsypref, TBbest, TBdivTBmsy, BdivBmsypref, TAC, TCbest, ERbest, SSB, F, FdivFmsy, ) %>% #These are some of the metrics of interest, but this can be changed to select more if needed.
  left_join(tbl_df(stock),by = c("stockid", "stocklong")) %>%
  left_join(tbl_df(area), by = "areaid") %>%
  select(-inmyersdb, -myersstockid, -alternateareaname) %>% 
  filter(stockid == 'SWORDSATL') %>% #We are only interested in "country == multinational", so removing the two countries that have pelagic stock assessments that are not multinational.
  select(stockid, year, TCbest)
   #Not one of the RFMOs we're interested in, so removing it.

swordsatl.ram.dbase <- swordsatl.ram.ts 

write_csv(swordsatl.ram.dbase, "/Users/conne/Documents/Fisheries/fish_stuff/data/billfish/swordsatl_catch.csv")

# Note: only through 2013, updating with more recent numbers and re-saving file

```

## WMARLINATL (no update)

```{r}
# Extract main RAM timeseries, with BdivBmsypref and UdivUmsypref
wmarlinatl.ram.ts <- timeseries_values_views %>%
  tbl_df() %>%
  select(stockid, stocklong, year, UdivUmsypref, TBbest, TBdivTBmsy, BdivBmsypref, TAC, TCbest, ERbest, SSB, F, FdivFmsy, ) %>% #These are some of the metrics of interest, but this can be changed to select more if needed.
  left_join(tbl_df(stock),by = c("stockid", "stocklong")) %>%
  left_join(tbl_df(area), by = "areaid") %>%
  select(-inmyersdb, -myersstockid, -alternateareaname) %>% 
  filter(stockid == 'WMARLINATL') %>% #We are only interested in "country == multinational", so removing the two countries that have pelagic stock assessments that are not multinational.
  select(stockid, year, TCbest)
   #Not one of the RFMOs we're interested in, so removing it.

wmarlinatl.ram.dbase <- wmarlinatl.ram.ts 

write_csv(wmarlinatl.ram.dbase, "/Users/conne/Documents/Fisheries/fish_stuff/data/billfish/wmarlinatl_catch.csv")

# Note: only through 2010, updating with more recent numbers and re-saving file
```

