---
title: "Combined Catch"
author: "Conner Smith"
date: "7/11/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)

library(tidyverse)
library(here)
library(forcats)

colors <- c("olivedrab3", "steelblue4", "coral2")
names(colors) = c("Shark", "Billfish", "Tuna")
```

## Read in the Data 

```{r}
shark_catch <- read_csv(here('data', 'shark', 'all_shark_catch.csv'))

billfish_catch <- read_csv(here('data', 'billfish', 'all_billfish_catch.csv'))

tuna_catch <- read_csv(here('data', 'tuna', 'all_tuna_catch.csv'))

all_catch <- data.frame(tuna_catch) %>% 
  bind_rows(billfish_catch,
            shark_catch) %>% 
  mutate(tax_grp = case_when(tax_grp == "tuna" ~ "Tuna",
                                tax_grp == "billfish" ~ "Billfish",
                                tax_grp == "shark" ~ "Shark")) %>% 
  drop_na()

all_catch_condensed <- all_catch %>% 
  group_by(year, tax_grp) %>% 
  summarize(catch = sum(catch)) %>% 
  filter(year %in% c(1975:2018))
```


## Catch for All Stocks 

```{r}
all_catch_plot <- ggplot(all_catch_condensed, aes(x = year, y = catch, 
                                fill = fct_reorder(tax_grp, catch))) +
  geom_area() +
  scale_y_continuous(labels = scales::label_comma(scale = .1)) +
  scale_fill_manual(values = colors) +
  labs(x = "Year", y = "Catch (metric tons)", fill = "Taxonomy Group") +
  theme_minimal()
all_catch_plot

ggsave("all_catch.png", plot = all_catch_plot, bg = 'white')

```

## Catch by RFMO 

```{r}
all_catch_rfmo <- all_catch %>% 
  group_by(year, rfmo, tax_grp) %>% 
  filter(rfmo != "CCSBT") %>% 
  summarize(catch = sum(catch)) %>% 
  filter(year %in% c(1975:2019))

rfmo_catch_plot <- ggplot(all_catch_rfmo, aes(x = year, y = catch, 
                           fill = fct_reorder(tax_grp, catch))) +
  geom_area() +
  facet_wrap(~ rfmo, ncol = 2) +
  scale_y_continuous(labels = scales::label_comma(scale = .1)) +
  scale_fill_manual(values = colors) +
  labs(x = "Year", y = "Catch (metric tons)", fill = "Taxonomy Group") +
  theme_minimal()
rfmo_catch_plot

ggsave("rfmo_catch.png", plot = rfmo_catch_plot, bg = 'white')
```

