---
title: "IATTC Assessments"
author: "Conner Smith"
date: "6/16/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(here)
library(tidyverse)

load(here("data", "DBdata[asmt][v4.495].RData"))
```


## BIGEYEEPAC (no update, jsut pulling catch)

```{r setup, include=FALSE}
# RAM datasets to use
ram_datasets <- c('timeseries_values_views', 'stock', 'area', 'bioparams', 'timeseries_assessments_views',
                  'bioparams_values_views', 'assessor', 'management', 'assessment')
# Remove all unneccessary RAM data
rm(list = c(ls()[!(ls() %in% ram_datasets)]))

# Extract main RAM timeseries, with BdivBmsypref and UdivUmsypref
bigeyeepac.ram.ts <- timeseries_values_views %>%
  tbl_df() %>%
  select(stockid, stocklong, year, UdivUmsypref, TBbest, TBdivTBmsy, BdivBmsypref, TAC, TCbest, ERbest, SSB, F, FdivFmsy, ) %>% #These are some of the metrics of interest, but this can be changed to select more if needed.
  left_join(tbl_df(stock),by = c("stockid", "stocklong")) %>%
  left_join(tbl_df(area), by = "areaid") %>%
  select(-inmyersdb, -myersstockid, -alternateareaname) %>% 
  filter(stockid == 'BIGEYEEPAC') %>% #We are only interested in "country == multinational", so removing the two countries that have pelagic stock assessments that are not multinational.
  select(stockid, year, TCbest)
   #Not one of the RFMOs we're interested in, so removing it.

bigeyeepac.ram.dbase <- bigeyeepac.ram.ts 

write_csv(bigeyeepac.ram.dbase, "/Users/conne/Documents/Fisheries/fish_stuff/data/bigeyeepac_catch.csv")
```

## YFINEPAC 

```{r}
# RAM datasets to use
ram_datasets <- c('timeseries_values_views', 'stock', 'area', 'bioparams', 'timeseries_assessments_views',
                  'bioparams_values_views', 'assessor', 'management', 'assessment')
# Remove all unneccessary RAM data
rm(list = c(ls()[!(ls() %in% ram_datasets)]))

# Extract main RAM timeseries, with BdivBmsypref and UdivUmsypref
yfinepac.ram.ts <- timeseries_values_views %>%
  tbl_df() %>%
  select(stockid, stocklong, year, UdivUmsypref, TBbest, TBdivTBmsy, BdivBmsypref, TAC, TCbest, ERbest, SSB, F, FdivFmsy, ) %>% #These are some of the metrics of interest, but this can be changed to select more if needed.
  left_join(tbl_df(stock),by = c("stockid", "stocklong")) %>%
  left_join(tbl_df(area), by = "areaid") %>%
  select(-inmyersdb, -myersstockid, -alternateareaname) %>% 
  filter(stockid == 'YFINEPAC') %>% #We are only interested in "country == multinational", so removing the two countries that have pelagic stock assessments that are not multinational.
  select(stockid, year, TCbest)
   #Not one of the RFMOs we're interested in, so removing it.

yfinepac.ram.dbase <- yfinepac.ram.ts 

write_csv(yfinepac.ram.dbase, "/Users/conne/Documents/Fisheries/fish_stuff/data/yfinepac_catch.csv")
```

## STMARLINNEPAC (no update)

```{r}

# Extract main RAM timeseries, with BdivBmsypref and UdivUmsypref
stmarlinnepac.ram.ts <- timeseries_values_views %>%
  tbl_df() %>%
  select(stockid, stocklong, year, UdivUmsypref, TBbest, TBdivTBmsy, BdivBmsypref, TAC, TCbest, ERbest, SSB, F, FdivFmsy, ) %>% #These are some of the metrics of interest, but this can be changed to select more if needed.
  left_join(tbl_df(stock),by = c("stockid", "stocklong")) %>%
  left_join(tbl_df(area), by = "areaid") %>%
  select(-inmyersdb, -myersstockid, -alternateareaname) %>% 
  filter(stockid == 'STMARLINNEPAC') %>% #We are only interested in "country == multinational", so removing the two countries that have pelagic stock assessments that are not multinational.
  select(stockid, year, TCbest)
   #Not one of the RFMOs we're interested in, so removing it.

stmarlinnepac.ram.dbase <- stmarlinnepac.ram.ts 

write_csv(stmarlinnepac.ram.dbase, "/Users/conne/Documents/Fisheries/fish_stuff/data/stmarlinnepac_catch.csv")

# Ends in 2009
```

## STMARLINWCNPAC (no update)

```{r}

# Extract main RAM timeseries, with BdivBmsypref and UdivUmsypref
stmarlinwcnpac.ram.ts <- timeseries_values_views %>%
  tbl_df() %>%
  select(stockid, stocklong, year, UdivUmsypref, TBbest, TBdivTBmsy, BdivBmsypref, TAC, TCbest, ERbest, SSB, F, FdivFmsy, ) %>% #These are some of the metrics of interest, but this can be changed to select more if needed.
  left_join(tbl_df(stock),by = c("stockid", "stocklong")) %>%
  left_join(tbl_df(area), by = "areaid") %>%
  select(-inmyersdb, -myersstockid, -alternateareaname) %>% 
  filter(stockid == 'STMARLINWCNPAC') %>% #We are only interested in "country == multinational", so removing the two countries that have pelagic stock assessments that are not multinational.
  select(stockid, year, TCbest)
   #Not one of the RFMOs we're interested in, so removing it.

stmarlinwcnpac.ram.dbase <- stmarlinwcnpac.ram.ts 

write_csv(stmarlinnepac.ram.dbase, "/Users/conne/Documents/Fisheries/fish_stuff/data/stmarlinwcnpac_catch.csv")

# Ends in 2013
```
