---
title: "IOTC Assessments"
author: "Conner Smith"
date: "6/14/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(here)
library(tidyverse)

load(here("data", "DBdata[asmt][v4.495].RData"))
```

## ALBAIO

```{r setup, include=FALSE}
# RAM datasets to use
ram_datasets <- c('timeseries_values_views', 'stock', 'area', 'bioparams', 'timeseries_assessments_views',
                  'bioparams_values_views', 'assessor', 'management', 'assessment')
# Remove all unneccessary RAM data
rm(list = c(ls()[!(ls() %in% ram_datasets)]))

# Extract main RAM timeseries, with BdivBmsypref and UdivUmsypref
albaio.ram.ts <- timeseries_values_views %>%
  tbl_df() %>%
  select(stockid, stocklong, year, UdivUmsypref, TBbest, TBdivTBmsy, BdivBmsypref, TAC, TCbest, ERbest, SSB, F, FdivFmsy, ) %>% #These are some of the metrics of interest, but this can be changed to select more if needed.
  left_join(tbl_df(stock),by = c("stockid", "stocklong")) %>%
  left_join(tbl_df(area), by = "areaid") %>%
  select(-inmyersdb, -myersstockid, -alternateareaname) %>% 
  filter(scientificname == "Thunnus alalunga",
         areaid == "multinational-IOTC-IO") %>% #We are only interested in "country == multinational", so removing the two countries that have pelagic stock assessments that are not multinational.
  select(stockid:FdivFmsy, country)
   #Not one of the RFMOs we're interested in, so removing it.

albaio.ram.dbase <- albaio.ram.ts 

write_csv(albaio.ram.dbase, "/Users/conne/Documents/Fisheries/fish_stuff/data/albaio_timeseries_2016.csv")
```

## BIGEYEIO

```{r setup, include=FALSE}
# RAM datasets to use
ram_datasets <- c('timeseries_values_views', 'stock', 'area', 'bioparams', 'timeseries_assessments_views',
                  'bioparams_values_views', 'assessor', 'management', 'assessment')
# Remove all unneccessary RAM data
rm(list = c(ls()[!(ls() %in% ram_datasets)]))

# Extract main RAM timeseries, with BdivBmsypref and UdivUmsypref
bigeyeio.ram.ts <- timeseries_values_views %>%
  tbl_df() %>%
  select(stockid, stocklong, year, UdivUmsypref, TBbest, TBdivTBmsy, BdivBmsypref, TAC, TCbest, ERbest, SSB, F, FdivFmsy, ) %>% #These are some of the metrics of interest, but this can be changed to select more if needed.
  left_join(tbl_df(stock),by = c("stockid", "stocklong")) %>%
  left_join(tbl_df(area), by = "areaid") %>%
  select(-inmyersdb, -myersstockid, -alternateareaname) %>% 
  filter(stockid == 'BIGEYEIO') %>% #We are only interested in "country == multinational", so removing the two countries that have pelagic stock assessments that are not multinational.
  select(stockid:FdivFmsy, country)
   #Not one of the RFMOs we're interested in, so removing it.

bigeyeio.ram.dbase <- bigeyeio.ram.ts 

write_csv(bigeyeio.ram.dbase, "/Users/conne/Documents/Fisheries/fish_stuff/data/bigeyeio_timeseries_2016.csv")
```

## SKJCIO

```{r setup, include=FALSE}
# RAM datasets to use
ram_datasets <- c('timeseries_values_views', 'stock', 'area', 'bioparams', 'timeseries_assessments_views',
                  'bioparams_values_views', 'assessor', 'management', 'assessment')
# Remove all unneccessary RAM data
rm(list = c(ls()[!(ls() %in% ram_datasets)]))

# Extract main RAM timeseries, with BdivBmsypref and UdivUmsypref
skjcio.ram.ts <- timeseries_values_views %>%
  tbl_df() %>%
  select(stockid, stocklong, year, UdivUmsypref, TBbest, TBdivTBmsy, BdivBmsypref, TAC, TCbest, ERbest, SSB, F, FdivFmsy, ) %>% #These are some of the metrics of interest, but this can be changed to select more if needed.
  left_join(tbl_df(stock),by = c("stockid", "stocklong")) %>%
  left_join(tbl_df(area), by = "areaid") %>%
  select(-inmyersdb, -myersstockid, -alternateareaname) %>% 
  filter(stockid == 'SKJCIO') %>% #We are only interested in "country == multinational", so removing the two countries that have pelagic stock assessments that are not multinational.
  select(stockid:FdivFmsy, country)
   #Not one of the RFMOs we're interested in, so removing it.

skjcio.ram.dbase <- skjcio.ram.ts 

write_csv(skjcio.ram.dbase, "/Users/conne/Documents/Fisheries/fish_stuff/data/skjcio_timeseries_2016.csv")
```

## YFINEIO

```{r}
# RAM datasets to use
ram_datasets <- c('timeseries_values_views', 'stock', 'area', 'bioparams', 'timeseries_assessments_views',
                  'bioparams_values_views', 'assessor', 'management', 'assessment')
# Remove all unneccessary RAM data
rm(list = c(ls()[!(ls() %in% ram_datasets)]))

# Extract main RAM timeseries, with BdivBmsypref and UdivUmsypref
yfineio.ram.ts <- timeseries_values_views %>%
  tbl_df() %>%
  select(stockid, stocklong, year, UdivUmsypref, TBbest, TBdivTBmsy, BdivBmsypref, TAC, TCbest, ERbest, SSB, F, FdivFmsy, ) %>% #These are some of the metrics of interest, but this can be changed to select more if needed.
  left_join(tbl_df(stock),by = c("stockid", "stocklong")) %>%
  left_join(tbl_df(area), by = "areaid") %>%
  select(-inmyersdb, -myersstockid, -alternateareaname) %>% 
  filter(stockid == 'YFINEIO') %>% #We are only interested in "country == multinational", so removing the two countries that have pelagic stock assessments that are not multinational.
  select(stockid:FdivFmsy, country)
   #Not one of the RFMOs we're interested in, so removing it.

yfineio.ram.dbase <- yfineio.ram.ts 

write_csv(yfineio.ram.dbase, "/Users/conne/Documents/Fisheries/fish_stuff/data/yfineio_timeseries_2016.csv")
```


## BLKMARLINIO

```{r}
# RAM datasets to use
ram_datasets <- c('timeseries_values_views', 'stock', 'area', 'bioparams', 'timeseries_assessments_views',
                  'bioparams_values_views', 'assessor', 'management', 'assessment')
# Remove all unneccessary RAM data
rm(list = c(ls()[!(ls() %in% ram_datasets)]))

# Extract main RAM timeseries, with BdivBmsypref and UdivUmsypref
blkmarlinio.ram.ts <- timeseries_values_views %>%
  tbl_df() %>%
  select(stockid, stocklong, year, UdivUmsypref, TBbest, TBdivTBmsy, BdivBmsypref, TAC, TCbest, ERbest, SSB, F, FdivFmsy, ) %>% #These are some of the metrics of interest, but this can be changed to select more if needed.
  left_join(tbl_df(stock),by = c("stockid", "stocklong")) %>%
  left_join(tbl_df(area), by = "areaid") %>%
  select(-inmyersdb, -myersstockid, -alternateareaname) %>% 
  filter(stockid == 'BLKMARLINIO') %>% #We are only interested in "country == multinational", so removing the two countries that have pelagic stock assessments that are not multinational.
  select(stockid:FdivFmsy, country)
   #Not one of the RFMOs we're interested in, so removing it.

blkmarlinio.ram.dbase <- blkmarlinio.ram.ts 

write_csv(blkmarlinio.ram.dbase, "/Users/conne/Documents/Fisheries/fish_stuff/data/blkmarlinio_timeseries_2014.csv")
```

## BMARLINIO

```{r}
# RAM datasets to use
ram_datasets <- c('timeseries_values_views', 'stock', 'area', 'bioparams', 'timeseries_assessments_views',
                  'bioparams_values_views', 'assessor', 'management', 'assessment')
# Remove all unneccessary RAM data
rm(list = c(ls()[!(ls() %in% ram_datasets)]))

# Extract main RAM timeseries, with BdivBmsypref and UdivUmsypref
bmarlinio.ram.ts <- timeseries_values_views %>%
  tbl_df() %>%
  select(stockid, stocklong, year, UdivUmsypref, TBbest, TBdivTBmsy, BdivBmsypref, TAC, TCbest, ERbest, SSB, F, FdivFmsy, ) %>% #These are some of the metrics of interest, but this can be changed to select more if needed.
  left_join(tbl_df(stock),by = c("stockid", "stocklong")) %>%
  left_join(tbl_df(area), by = "areaid") %>%
  select(-inmyersdb, -myersstockid, -alternateareaname) %>% 
  filter(stockid == 'BMARLINIO') %>% #We are only interested in "country == multinational", so removing the two countries that have pelagic stock assessments that are not multinational.
  select(stockid:FdivFmsy, country)
   #Not one of the RFMOs we're interested in, so removing it.

bmarlinio.ram.dbase <- bmarlinio.ram.ts 

write_csv(bmarlinio.ram.dbase, "/Users/conne/Documents/Fisheries/fish_stuff/data/bmarlinio_timeseries_2014.csv")
```

## IPSAILIO (not in database)

## STMARLINIO (no update)

```{r}
# RAM datasets to use
ram_datasets <- c('timeseries_values_views', 'stock', 'area', 'bioparams', 'timeseries_assessments_views',
                  'bioparams_values_views', 'assessor', 'management', 'assessment')
# Remove all unneccessary RAM data
rm(list = c(ls()[!(ls() %in% ram_datasets)]))

# Extract main RAM timeseries, with BdivBmsypref and UdivUmsypref
stmarlinio.ram.ts <- timeseries_values_views %>%
  tbl_df() %>%
  select(stockid, stocklong, year, UdivUmsypref, TBbest, TBdivTBmsy, BdivBmsypref, TAC, TCbest, ERbest, SSB, F, FdivFmsy, ) %>% #These are some of the metrics of interest, but this can be changed to select more if needed.
  left_join(tbl_df(stock),by = c("stockid", "stocklong")) %>%
  left_join(tbl_df(area), by = "areaid") %>%
  select(-inmyersdb, -myersstockid, -alternateareaname) %>% 
  filter(stockid == 'STMARLINIO') %>% #We are only interested in "country == multinational", so removing the two countries that have pelagic stock assessments that are not multinational.
  select(stockid, year, TCbest)
   #Not one of the RFMOs we're interested in, so removing it.

stmarlinio.ram.dbase <- stmarlinio.ram.ts 

write_csv(stmarlinio.ram.dbase, "/Users/conne/Documents/Fisheries/fish_stuff/data/stmarlinio_catch.csv")

# Note: only through 2014, updating with more recent numbers and re-saving file
```


## SWORDIO

```{r}
# Extract main RAM timeseries, with BdivBmsypref and UdivUmsypref
swordio.ram.ts <- timeseries_values_views %>%
  tbl_df() %>%
  select(stockid, stocklong, year, UdivUmsypref, TBbest, TBdivTBmsy, BdivBmsypref, TAC, TCbest, ERbest, SSB, F, FdivFmsy, ) %>% #These are some of the metrics of interest, but this can be changed to select more if needed.
  left_join(tbl_df(stock),by = c("stockid", "stocklong")) %>%
  left_join(tbl_df(area), by = "areaid") %>%
  select(-inmyersdb, -myersstockid, -alternateareaname) %>% 
  filter(stockid == 'SWORDIO') %>% #We are only interested in "country == multinational", so removing the two countries that have pelagic stock assessments that are not multinational.
  select(stockid:FdivFmsy, country)
   #Not one of the RFMOs we're interested in, so removing it.

swordio.ram.dbase <- swordio.ram.ts 

write_csv(swordio.ram.dbase, "/Users/conne/Documents/Fisheries/fish_stuff/data/swordio_timeseries_2014.csv")
```

