---
title: "Kobe Plots"
author: "Conner Smith"
date: "6/27/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(here)
library(cowplot)
library(patchwork)
library(png)
library(jpeg)
library(ggrepel)

kobe_values <- read_csv(here("data", "kobe_data_complete.csv"))
```

## Tuna 

```{r}

tuna_logo <- readPNG(here("data", "tuna", "red_tuna.png"), native = TRUE)

tuna_kobe <- kobe_values %>% 
  filter(tax_grp == 'tuna') %>% 
  select(stock_name, f_msy, b_msy, msy) %>% 
  rename(MSY = msy)

tuna_summary <- tuna_kobe %>% 
  drop_na() %>%  
  mutate(mean_b = mean(b_msy),
            mean_f = mean(f_msy)) %>% 
  mutate(med_b = median(b_msy),
            med_f = median(f_msy))


tuna_plot <- ggplot(data = tuna_kobe, aes(x = b_msy, y = f_msy, label = stock_name)) +
  geom_point(aes(size = MSY), color = 'coral2') +
  geom_text_repel(check_overlap = T, size = 3) +
  geom_hline(yintercept = 1,linetype = 2) +
  geom_vline(xintercept = 1,linetype = 2) +
  theme_classic() +
  theme(panel.border = element_rect(colour = "black", fill = NA, size = 1)) +
  labs(y = "F/Fmsy",
       x = "B/Bmsy")

tuna_plot_image <- tuna_plot +
  inset_element(tuna_logo,
                left = 0.5,
                bottom = 0.7,
                right = 0.95,
                top = 0.95)
tuna_plot_image

ggsave("tuna_kobe.png", plot = tuna_plot_image, bg = 'white')

#ggdraw() +
 # draw_plot(tuna_plot,x = 0, y = 0, width = 1, height = 0.85) +
  #draw_image(tuna_logo,x = 0.75, y = 0.75, width = 0.25, height = 0.25)  


```

## Billfish

```{r}

billfish_logo <- readJPEG(here("data", "billfish", "sword_blue.jpg"), native = TRUE)

billfish_kobe <- kobe_values %>% 
  filter(tax_grp == 'billfish') %>% 
  select(stock_name, f_msy, b_msy, msy) %>% 
  rename(MSY = msy) 

billfish_summary <- billfish_kobe %>% 
  drop_na() %>%  
  mutate(mean_b = mean(b_msy),
            mean_f = mean(f_msy)) %>% 
  mutate(med_b = median(b_msy),
            med_f = median(f_msy))

billfish_plot <- ggplot(data = billfish_kobe, aes(x = b_msy, y = f_msy, label = stock_name)) +
  geom_point(aes(size = MSY), color = "steelblue4") +
  geom_text_repel(check_overlap = T, size = 3) +
  geom_hline(yintercept = 1,linetype = 2) +
  geom_vline(xintercept = 1,linetype = 2) +
  theme_classic() +
  theme(panel.border = element_rect(colour = "black", fill = NA, size = 1)) +
  labs(y = "F/Fmsy",
       x = "B/Bmsy")

billfish_plot_image <- billfish_plot +
  inset_element(billfish_logo,
                left = 0.5,
                bottom = 0.7,
                right = 0.95,
                top = 0.95)
billfish_plot_image

ggsave("billfish_kobe.png", plot = billfish_plot_image, bg = 'white')

#ggdraw() +
  #draw_plot(billfish_plot,x = 0, y = 0, width = 1, height = 0.85) +
  #draw_image(billfish_logo,x = 0.75, y = 0.75, width = 0.25, height = 0.25)  
```


## Shark

```{r}

shark_logo <- readJPEG(here("data", "shark", "grn_shark.jpg"), native = TRUE)
  
shark_kobe <- kobe_values %>% 
  filter(tax_grp == 'shark') %>% 
  select(stock_name, f_msy, b_msy, msy) %>% 
  rename(MSY = msy) %>% 
  replace_na(list(MSY = 0))

shark_summary <- shark_kobe %>% 
  drop_na() %>%  
  mutate(mean_b = mean(b_msy),
            mean_f = mean(f_msy)) %>% 
  mutate(med_b = median(b_msy),
            med_f = median(f_msy))

shark_plot <- ggplot(data = shark_kobe, 
                     aes(x = b_msy, y = f_msy, label = stock_name)) +
  geom_point(aes(size = MSY), color = "olivedrab3") +
  geom_text_repel(check_overlap = T, size = 3) +
  geom_hline(yintercept = 1,linetype = 2) +
  geom_vline(xintercept = 1,linetype = 2) +
  theme_classic() +
  theme(panel.border = element_rect(colour = "black", fill = NA, size = 1)) +
  labs(y = "F/Fmsy",
       x = "B/Bmsy")

shark_plot_image <- shark_plot +
  inset_element(shark_logo,
                left = 0.5,
                bottom = 0.7,
                right = 0.95,
                top = 0.95)
shark_plot_image

ggsave("shark_kobe.png", plot = shark_plot_image, bg = 'white')

#ggdraw() +
 # draw_plot(shark_plot,x = 0, y = 0, width = 1, height = 0.85) +
 # draw_image(shark_logo,x = 0.75, y = 0.75, width = 0.25, height = 0.25)  
```

