---
title: "SBT Filter"
author: "Conner Smith"
date: "6/1/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(here)
library(tidyverse)

load(here("data", "DBdata[asmt][v4.495].RData"))
```


```{r setup, include=FALSE}
# RAM datasets to use
ram_datasets <- c('timeseries_values_views', 'stock', 'area', 'bioparams', 'timeseries_assessments_views',
                  'bioparams_values_views', 'assessor', 'management', 'assessment')
# Remove all unneccessary RAM data
rm(list = c(ls()[!(ls() %in% ram_datasets)]))

# Extract main RAM timeseries, with BdivBmsypref and UdivUmsypref
ram.ts <- timeseries_values_views %>%
  tbl_df() %>%
  select(stockid, stocklong, year, UdivUmsypref, BdivBmsypref, TAC, TCbest, ERbest, SSB) %>% #These are some of the metrics of interest, but this can be changed to select more if needed.
  left_join(tbl_df(stock),by = c("stockid", "stocklong")) %>%
  left_join(tbl_df(area), by = "areaid") %>%
  select(-inmyersdb, -myersstockid, -alternateareaname) %>% 
  filter(scientificname == "Thunnus maccoyii") %>% 
  filter(country != "Canada" & country != "USA") %>% #We are only interested in "country == multinational", so removing the two countries that have pelagic stock assessments that are not multinational.
  filter(areatype != "ICES") #Not one of the RFMOs we're interested in, so removing it.

ram.dbase <- ram.ts 
```

