---
title: "WCPFC Stock Assessments"
author: "Conner Smith"
date: "5/27/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(here)
library(tidyverse)
library(janitor)

load(here("data", "DBdata[asmt][v4.495].RData"))
```

## ALBASPAC Catch Calculations From Yearbook 

```{r}
spac_catch <- read_csv(here("data", "XLS_SouthPacific.csv")) %>% 
  clean_names()

albaspac_catch <- spac_catch %>% 
  group_by(sp_code, yy) %>% 
  filter(sp_code == "ALB") %>% 
  summarize(catch = sum(sp_mt)) %>% 
  rename(year = yy,
         stockid = sp_code) %>% 
  mutate(stockid = case_when(stockid == "ALB" ~ "ALBASPAC"))
 

write_csv(albaspac_catch, "/Users/conne/Documents/Fisheries/fish_stuff/data/albaspac_catch.csv")
  
```


## ALBSPAC

```{r setup, include=FALSE}
# RAM datasets to use
ram_datasets <- c('timeseries_values_views', 'stock', 'area', 'bioparams', 'timeseries_assessments_views',
                  'bioparams_values_views', 'assessor', 'management', 'assessment')
# Remove all unneccessary RAM data
rm(list = c(ls()[!(ls() %in% ram_datasets)]))

# Extract main RAM timeseries, with BdivBmsypref and UdivUmsypref
albaspac.ram.ts <- timeseries_values_views %>%
  tbl_df() %>%
  select(stockid, stocklong, year, UdivUmsypref, TBbest, TBdivTBmsy, BdivBmsypref, TAC, TCbest, ERbest, SSB, F, FdivFmsy, ) %>% #These are some of the metrics of interest, but this can be changed to select more if needed.
  left_join(tbl_df(stock),by = c("stockid", "stocklong")) %>%
  left_join(tbl_df(area), by = "areaid") %>%
  select(-inmyersdb, -myersstockid, -alternateareaname) %>% 
  filter(scientificname == "Thunnus alalunga",
         areaid == "multinational-WCPFC-SPAC") %>% #We are only interested in "country == multinational", so removing the two countries that have pelagic stock assessments that are not multinational.
  select(stockid:FdivFmsy, country)
   #Not one of the RFMOs we're interested in, so removing it.

albaspac.ram.dbase <- albaspac.ram.ts 

write_csv(albaspac.ram.dbase, "/Users/conne/Documents/Fisheries/fish_stuff/data/albaspac_timeseries_2015.csv")
```


## BIGEYECWPAC Catch Calculations From Yearbook 

```{r}
bigeyecwpac_catch <- read_csv(here("data", "XLS_WCPO.csv")) %>% 
  clean_names()

bigeyecwpac_catch <- bigeyecwpac_catch %>% 
  group_by(sp_code, yy) %>% 
  filter(sp_code == "BET") %>% 
  summarize(catch = sum(sp_mt)) %>% 
  rename(year = yy,
         stockid = sp_code) %>% 
  mutate(stockid = case_when(stockid == "BET" ~ "BIGEYECWPAC"))
 

write_csv(bigeyecwpac_catch, "/Users/conne/Documents/Fisheries/fish_stuff/data/bigeyecwpac_catch.csv")
```

## RAM data for BIGEYECWPAC

```{r setup, include=FALSE}
# RAM datasets to use
ram_datasets <- c('timeseries_values_views', 'stock', 'area', 'bioparams', 'timeseries_assessments_views',
                  'bioparams_values_views', 'assessor', 'management', 'assessment')
# Remove all unneccessary RAM data
rm(list = c(ls()[!(ls() %in% ram_datasets)]))

# Extract main RAM timeseries, with BdivBmsypref and UdivUmsypref
bigeyecwpac.ram.ts <- timeseries_values_views %>%
  tbl_df() %>%
  select(stockid, stocklong, year, UdivUmsypref, TBbest, TBdivTBmsy, BdivBmsypref, TAC, TCbest, ERbest, SSB, F, FdivFmsy, ) %>% #These are some of the metrics of interest, but this can be changed to select more if needed.
  left_join(tbl_df(stock),by = c("stockid", "stocklong")) %>%
  left_join(tbl_df(area), by = "areaid") %>%
  select(-inmyersdb, -myersstockid, -alternateareaname) %>% 
  filter(stockid == 'BIGEYECWPAC') %>% #We are only interested in "country == multinational", so removing the two countries that have pelagic stock assessments that are not multinational.
  select(stockid:FdivFmsy, country)
   #Not one of the RFMOs we're interested in, so removing it.

bigeyecwpac.ram.dbase <- bigeyecwpac.ram.ts 

write_csv(bigeyecwpac.ram.dbase, "/Users/conne/Documents/Fisheries/fish_stuff/data/bigeyecwpac_timeseries_2015.csv")
```


## SKJCWPAC from yearbook 

```{r}
skjcwpac_catch <- read_csv(here("data", "XLS_WCPO.csv")) %>% 
  clean_names()

skjcwpac_catch <- skjcwpac_catch %>% 
  group_by(sp_code, yy) %>% 
  filter(sp_code == "SKJ") %>% 
  summarize(catch = sum(sp_mt)) %>% 
  rename(year = yy,
         stockid = sp_code) %>% 
  mutate(stockid = case_when(stockid == "SKJ" ~ "SKJCWPAC"))
 

write_csv(skjcwpac_catch, "/Users/conne/Documents/Fisheries/fish_stuff/data/skjcwpac_catch.csv")
```


## YFINCWPAC from yearbook 

```{r}
yfincwpac_catch <- read_csv(here("data", "XLS_WCPO.csv")) %>% 
  clean_names()

yfincwpac_catch <- yfincwpac_catch %>% 
  group_by(sp_code, yy) %>% 
  filter(sp_code == "YFT") %>% 
  summarize(catch = sum(sp_mt)) %>% 
  rename(year = yy,
         stockid = sp_code) %>% 
  mutate(stockid = case_when(stockid == "YFT" ~ "YFINCWPAC"))
 

write_csv(yfincwpac_catch, "/Users/conne/Documents/Fisheries/fish_stuff/data/yfincwpac_catch.csv")
```

```{r}
# RAM datasets to use
ram_datasets <- c('timeseries_values_views', 'stock', 'area', 'bioparams', 'timeseries_assessments_views',
                  'bioparams_values_views', 'assessor', 'management', 'assessment')
# Remove all unneccessary RAM data
rm(list = c(ls()[!(ls() %in% ram_datasets)]))

# Extract main RAM timeseries, with BdivBmsypref and UdivUmsypref
yfincwpac.ram.ts <- timeseries_values_views %>%
  tbl_df() %>%
  select(stockid, stocklong, year, UdivUmsypref, TBbest, TBdivTBmsy, BdivBmsypref, TAC, TCbest, ERbest, SSB, F, FdivFmsy, ) %>% #These are some of the metrics of interest, but this can be changed to select more if needed.
  left_join(tbl_df(stock),by = c("stockid", "stocklong")) %>%
  left_join(tbl_df(area), by = "areaid") %>%
  select(-inmyersdb, -myersstockid, -alternateareaname) %>% 
  filter(stockid == 'YFINCWPAC') %>% #We are only interested in "country == multinational", so removing the two countries that have pelagic stock assessments that are not multinational.
  select(stockid:FdivFmsy, country)
   #Not one of the RFMOs we're interested in, so removing it.

yfincwpac.ram.dbase <- yfincwpac.ram.ts 

write_csv(yfincwpac.ram.dbase, "/Users/conne/Documents/Fisheries/fish_stuff/data/yfincwpac_timeseries_2015.csv")
```

## STMARLINSWPO (catch only)

```{r}
stmarlinswpo_catch <- read_csv(here("data", "XLS_WCPFC.csv")) %>% 
  clean_names()

stmarlinswpo_catch <- stmarlinswpo_catch %>% 
  group_by(sp_code, yy) %>% 
  filter(sp_code == "MLS") %>% 
  summarize(catch = sum(sp_mt)) %>% 
  rename(year = yy,
         stockid = sp_code) %>% 
  mutate(stockid = case_when(stockid == "MLS" ~ "STMARLINSWPO"))
 

write_csv(stmarlinswpo_catch, "/Users/conne/Documents/Fisheries/fish_stuff/data/stmarlinswpo_catch.csv")
```


